spring:
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.yml
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:h2:mem:city-country
    username: sa
    password: password
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB
server:
  port: 8081
app:
  pageSize: 10
